version: '3'
services:
  irisapi:
    image: ${DOCKER_REGISTRY}/${DOCKER_USERNAME}/irisapisimplondocker:${DOCKER_TAG}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    environment:
      - PORT=8000
