version: '3'
services:
  irisapi:
    image: 'elicontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6614b9f8aa9d4e2fad1aa6405711655e }}/irisapisimplondocker:${{ github.sha }}'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.8.12-buster
    volumes:
      - .:/app
    ports:
      - "${PORT}:8000"
    environment:
      - PORT=8000
