name: Build and deploy container app to Azure Web App - elidockerapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://elicontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6614b9f8aa9d4e2fad1aa6405711655e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1eefb976cac54a028debfbd7825d1f1f }}

    - name: Build and push container image to registry using Docker Compose
      run: |
        export DOCKER_REGISTRY=https://elicontainer.azurecr.io/
        export DOCKER_USERNAME=${{ secrets.AzureAppService_ContainerUsername_6614b9f8aa9d4e2fad1aa6405711655e }}
        export DOCKER_TAG=${{ github.sha }}
        export PORT=8000
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'elidockerapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a83bf080097a40edb3a4d4461238b7e5 }}
        images: 'elicontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6614b9f8aa9d4e2fad1aa6405711655e }}/irisapisimplondocker:${{ github.sha }}'
